ubuntu/gnome-shell-extension-appindicator

metadata.json
Confirmed by https://github.com/rgcjonas/gnome-shell-extension-appindicator/pull/61#issuecomment-261399433.
=> Works on Gnome 3.22 too

appIndicator.js
Tested on GNOME Shell 3.24.1 on ArchLinux on both HiDPI and regular displays.
=> Issue #71: Add support for HiDPI screens

appIndicator.js
Always adding "-panel" to the end of icon_name assumes that icon_name + "-panel" exists or should exist. That is not always the case.
This commit 1st checks to see if icon_name +  "-panel" is in the current icon theme and if it is fine use it, otherwise it will use icon_name as is.
=> Don't add "-panel" to the end of the icon_name unless icon_name is not in the current theme

appIndicator.js, indicatorStatusIcon.js, interfaces-xml/StatusNotifierItem.xml
Sends a SecondaryActivate dbus event to the application when single middle mouse clicking appindicator without showing the appindicator menu.
=> Middle mouse click SecondaryActivate

appIndicator.js
Manually scale the icon if it was passed as a pixbuf.
=> Manually scale the icon if it was passed as a pixbuf

interfaces-xml/StatusNotifierWatcher.xml, statusNotifierWatcher.js, util.js
Some indicators (*coff*, dropbox, *coff*) do not re-register again
when the plugin is enabled/disabled, thus we need to manually look
for the objects in the session bus that implements the
StatusNotifierItem interface...
This fixes issue #75, workarounding the applications problem.
Including also some other cleanups.
This won't apply to bugged apps that are confined (i.e. in snaps) since we won't be able to introspect them. The only option with these is trying to access to the standard `/StatusNotifyItem` path and see if properties are set. Less priority for now, though.
=> statusNotifierWatcher: seek for SNIs in the bus to ensure we have them all

appIndicator.js
The scale factor on HiDPI displays only needs to be applied to pixmap indicator icons.
When the icon is obtained from the current theme then the size should be correct based on the system scaling values.
The fix was tested with a x2 scaling and x1 scaling.
Please advise on wether there is a better way of solving the problem and if my understanding is correct.
=> Issue #110: Fix icons vertically stretched

interfaces.js
As strings are guaranteed to use UTF-8 in the GNOME platform, generic file APIs
like g_file_load_contents() return raw data instead. Since gjs' recent update to
mozjs60, this data is now returned as Uint8Array which cannot simply be treated
as string - its toString() method boils down to arr.join(',') - so use gjs' new
ByteArray module to explicitly convert the data.
Fixes: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/150
=> interfaces: Explicitly convert raw data to strings

appIndicator.js, dbusMenu.js, extension.js, iconCache.js, indicator-test-tool/testTool.js, indicatorStatusIcon.js, metadata.json, statusNotifierWatcher.js, util.js
As per upstream changes [1], Lang.Class'es aren't supported anymore to extend
GNOME Shell objects, making dash-to-dock not to work anymore.
Keeping compatibility with older versions isn't feasible with a reasonable
quantiy of work, so better to move everything to the new syntax (supported
since GNOME Shell 3.30)
[1] https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361
=> appindicators: rewrite classes using pure ES6 classes

util.js
Optimize expression
```js
typeof x === "undefined" || !x
```
equal
```js
!x
```
because
```js
!undefined// true
```
=> Remove needless typeof undefinded

appIndicator.js
Currently appindicator throws errors when the theme doesn't
provide an icon, even though there is a fallback pixmap
from the application.
With this the error will only get thrown if neither is
provided.
Fixes #145
=> appIndicator: disable `unable to lookup icon for ...` message

README.md
gnome-shell-extension-tool is deprecated (errors out on ubuntu 19.10 when trying to use it), use gnome-extensions instead
=> Readme - gnome-shell-extension-tool is deprecated

appIndicator.js
This was wrongly added in cb1abf5955. The overlay icon is not mandatory
and many applications do not set one, so lets not spam the log.
=> appIndicator: Remove warning on missing overlay icon

extension.js, statusNotifierWatcher.js
Added code to handle the case when the name org.kde.StatusNotifierWatcher can't be owned (for whatever reason), and thus the indicators disappear when the lock screen is engaged (manually or otherwise).
This is by no means a final approach, and it may revive some of the side-effects that gave birth to the watchDog object, but I think it's a start.
=> FIX#107: Indicator stops working after screen lock

appIndicator.js
**[why]**
With commit
bac3f1c0 appIndicator: Support fixed-size icons
a bug has been introduced, that is triggered if an icon can not be
loaded:
gnome-shell[17071]: JS ERROR: TypeError: Util.Logger.fatal is not a function
**[how]**
Our util.js has indeed no fatal(), but only these:
```
debug(message)
warn(message)
error(message)
critical(message)
```
So I reckon ``critical()`` is what has been meant.
=> appIndicator: Fix runtime error when icon can not be loaded

appIndicator.js
**[why]**
The spacing between icons shown by us seems a bit too wide.
A lot of people would rather have a smaller distance between the icons.
**[how]**
Top bar buttons have a given padding. Additionally to that we pad the
icons a bit more. That padding can be removed, without violating the design
goals imposed by the top bar (i.e. menu button padding).
This makes the visual appearance a bit more pleasing. And still
conforming.
I'm sure people will want to further decrease the distance, but that
will violate the required button padding. A composite button would have
to be used then instead (like the aggregate menu does).
=> feature: Remove unneeded padding

appIndicator.js, extension.js
Gnome Shell enables the extensions before the desktop itself is ready to accept widgets. This can result in errors. In the case of appindicator, it results in applications that are launched during startup not showing an indicator because, when the extension tries to add the icon to the Gnome Shell interface, it still isn't ready for that, thus failing. But other applications, launched after the Shell has completed the startup process, will work fine.
This patch fixes this by checking in the `enable()` method if Gnome Shell is still starting up, in which case it waits until the `startup-complete` signal is triggered before continuing.
Fix #235
=> Wait until the desktop ends starting up

interfaces-xml/StatusNotifierWatcher.xml, statusNotifierWatcher.js
The KNotifications implementation of KStatusNotifierItem expects an Int32 property called `ProtocolVersion` to exist in `org.kde.StatusNotifierWatcher`.
If it doesn't exist, it tries to fall back to a legacy tray icon, and may cause other issues, such as https://github.com/ckb-next/ckb-next/issues/633 .
This behaviour can be seen here.
https://github.com/KDE/knotifications/blob/311cd94ab32b9a916cb86012bca669599878239a/src/kstatusnotifieritem.cpp#L880-L894
The expected protocol version is 0.
https://github.com/KDE/knotifications/blob/311cd94ab32b9a916cb86012bca669599878239a/src/kstatusnotifieritem.cpp#L786
This commit implements the property in the extension.
=> kstatusnotifierwatcher: Implement ProtocolVersion property

metadata.json
This extension supports GNOME 40 without any change, please just mark it as supported in the metadata.json to be able to install it.
=> Add support for GNOME 40

metadata.json
This is a trivial change. Tested on Fedora 35 beta.
Fixes https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/307
=> Add support for GNOME 41

appIndicator.js, prefs.js, schemas/org.gnome.shell.extensions.appindicator.gschema.xml
I've added a section to the preferences that allows to change any icon with a custom icon from the current icon theme (if it exists)
here zoom, and TeamViewer as an example. If the "custom icon names" exist in the icon theme they will be used instead of the original icons. 
I'm not 100% sure I used the most elegant solution everywhere (I'm not so used to gjs) but it seems to work flawlessly
I think it is a cool feature especially for apps that cannot be themed otherwise, and works well together with the recent changes introduced (desaturation, contrast etc...)
=> Adds the possibility to change any icon with a custom icon from an icon theme

metadata.json
Works without a hitch in GNOME 43.alpha. No errors nor warnings reported in logs.
AppIndicator menu from [CLight GUI](https://github.com/nullobsi/clight-gui) shown in screenshot below as example of it working correctly.
Using [FCGU](https://gitlab.com/fabiscafe/gnome-unstable) repo and [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) package [gnome-shell-extension-appindicator-gnome43](https://aur.archlinux.org/packages/gnome-shell-extension-appindicator-gnome43) to test.
=> List shell version 43 in metadata.json

appIndicator.js, pixmapsUtils.js
Optimize various cases when pixmap icons are used, so that we can reduce their memory impact and do less operations, avoiding to unpack the variants we don't care about.
=> Pixmap optimizations

appIndicator.js
This applies to all the versions < 44, where we only use GdkPixbuf's (to avoid StCache) to load the images.
Closes: #404
=> Use theme-node based icon lookup and colorize symbolic icons

appIndicator.js
In case the stage is not set we may not have proper signaling until the actor is mapped, what we care is having a proper style here though so let's wait for that
=> appIndicator: Wait for style change if no stage is set

appIndicator.js, indicatorStatusIcon.js
Avoid doing the conversion JS, as Clutter can handle this natively.
In case we don't have overlays (and then we don't need to create an emblemed
icon), we can avoid going through reading the texture, but just leave to
clutter the role of painting the ImageContent as it is.
Closes: #295
=> appIndicator Use Clutter to load RGBA Pixmap textures natively

appIndicator.js, dbusMenu.js, interfaces-xml/DBusMenu.xml, interfaces-xml/StatusNotifierItem.xml, interfaces-xml/StatusNotifierWatcher.xml, statusNotifierWatcher.js, util.js
Use base classes and optimize proxy so that we don't incur in gjs' automatic unpacking of big variants.
=> Refactor dbusMenu Client

dbusMenu.js, indicator-test-tool/testTool.js
Do not monitor changes when a menu is closed, nor update the widgets.
Only do it once a menu is opened.
=> Only update DBusMenu contents when menus are opened

appIndicator.js, indicator-test-tool/testTool.js, indicatorStatusIcon.js, statusNotifierWatcher.js, util.js
From main commit:
```
We used to always looking up for the icons ourself, somewhat duplicating
the shell work, it allowed to prevent shell caching of some files, but still
we can remove lots of deprecated code and handle things more smartly given
that texture-caching can be good in case of well-known files.
In short:
- named-only icons are now loaded through a Gio.ThemedIcon (and so cached)
- icons with custom theme are searched in provided path and behave just
like any other icon with full path as explained below.
- icons with a full icon path (provided by the theme or not) may be loaded
in different ways:
* Using a Gio.FileIcon if they are in non-writable areas (so we assume
that there are only a limited number of them) and they are cashed.
* using a StTextureCacheSkippingFileIcon in …
```
=> appIndicator: Refactor named icons lookup and loading

.eslintrc.yml, dbusMenu.js, statusNotifierWatcher.js, util.js
Try to reduce some initialization sync code that may lead to blocking UI.
=> Lazier init

metadata.json
As of 46.alpha I have found that adding 46 into the shell version allows appindicator to work on Gnome 46 with out any other intervention.
=> Update metadata.json for Gnome 46

iconCache.js
The comparison function is named `equal()`.
https://docs.gtk.org/gio/method.Icon.equal.html
Fixes this traceback:
```text
Apr 14 17:15:41 gnome-shell[2368055]: 
remmina-icon unable to update icon: TypeError: oldIcon.equals is not a function
Stack trace:
add@file:///.../appindicatorsupport@rgcjonas.gmail.com/iconCache.js:52:34
_cacheOrCreateIconByName@file:///.../appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1074:37
async*_createIcon@file:///.../appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1440:38
_createAndSetIcon@file:///.../appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1400:32
_updateIconByType@file:///.../appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1392:24
_updateIcon@file:///.../appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1469:24 …
```
=> iconCache: Gio.Icon.equal(), not .equals()

indicatorStatusIcon.js
Fixes #516
The problem is that both vfunc_button_press_event and vfunc_button_release_event call _maybeHandleDoubleClick the first time around, so a press+release becomes a double click. But the second time, this._indicator.supportsActivation has been set to true instead of undefined, so vfunc_button_release_event doesn't trigger the double click.
The deleted code cannot be useful because...
- if supportsActivation is false, _maybeHandleDoubleClick immediately returns EVENT_PROPAGATE
- if supportsActivation is true, vfunc_button_release_event skips _maybeHandleDoubleClick and returns EVENT_PROPAGATE
- if it's undefined and changes value, we get the aforementioned bug.
=> Fix first click being treated as both a single and double click by deleting vfunc_button_release_event

appIndicator.js
Since its presence may lead to a delay to handle the double click, let's try to check early if the application supports it or not.
As per https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/519#issuecomment-2049088209
/cc @jingw @plumlis
=> appIndicator: Try to introspect the application for Activate method support

indicatorStatusIcon.js, util.js
Both methods must be replaced in Gnome 46.
=> Replace add_actor and remove_actor

dbusMenu.js
It's not defined in all the implementations, so in case that we
have not, let's just ignore the error and avoid calling it again
Fixes: #502
=> dbusMenu: Handle missing AboutToShow gracefully

metadata.json
The extension appears to work for me with GNOME Shell 47 Beta
I did see this in my journal but I don't know if this is a new error:
```
Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
Stack trace:
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
@resource:///org/gnome/shell/ui/init.js:21:20
getProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:89:33
refreshProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:306:48
_refreshOwnProperties/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:192:32
_refreshOwnProperties@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu …
```
=> metadata: Mark compatible with GNOME Shell 47

appIndicator.js, dbusMenu.js
This patch show extra debug info for DBus; specifically, when some DBus calls fail, it shows the called address, object and interface, to allow to identify the misbehaving application.
=> Add extra debug info

trayIconsManager.js
Tray icons in the shell may not use RGBA visuals, so in such case we
need to set the proper background color or we'll just show them with
black background and this is an issue with light or custom themes
Fixes: #446
=> trayIconsManager: Use panel-matching background color for tray manager

appIndicator.js
Chromium and Electron apps do not implement the IconAccessibleDesc property and reply to the Get() method with a generic
org.freedesktop.DBus.Error.Failed
Rather than adding the generic error to the list of allowed errors, remove the filtering on the error type altogether.
Fixes: #534
LP: #2064698
=> Never log failure to retrieve an optional property
